source_dict = {'Pesticide and Groundwater Quality.txt': 'https://azdeq.gov/node/4677',
 'the_myth_of_safe-yield_0.pdf': 'https://morrisoninstitute.asu.edu/sites/default/files/the_myth_of_safe-yield_0.pdf',
 'NAU WaTER Lab.pdf': 'http://www.dymondlab.com/research.html',
 'Tri-University Water Recharge Collaboration.pdf': 'https://ccass.arizona.edu/arizona-tri-university-recharge-and-water-reliability-project',
 'Yuma_Factsheet_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Yuma_Factsheet_01_2024.pdf',
 'Factsheet_Development_Overview.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-03/Factsheet_Development_Overview.pdf',
 'Maricopa_Factsheet_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Maricopa_Factsheet_01_2024.pdf',
 'Pima_6-page_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Pima_6-page_01_2024.pdf',
 'Cochise_Factsheet_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Cochise_Factsheet_01_2024.pdf',
 'Mohave_8-page_01_2024.pdf': 'https://wrrc.arizona.edu/publication/arizona-water-factsheet-mohave-county',
 'Yavapai_8-page_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Yavapai_8-page_01_2024.pdf',
 'Graham_Factsheet_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Graham_Factsheet_01_2024.pdf',
 'Greenlee_Factsheet_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Greenlee_Factsheet_01_2024.pdf',
 'Gila_Factsheet_01_2024.pdf': 'https://wrrc.arizona.edu/publication/arizona-water-factsheet-gila-county',
 'La Paz_Factsheet_01_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/La%20Paz_Factsheet_01_2024.pdf',
 'Santa Cruz_02.2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-02/Santa%20Cruz_02.2024.pdf',
 'Coconino_Factsheet_03_2024.pdf': 'https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-03/Coconino_Factsheet_03_2024.pdf',
 'Galveston Bay Report Card.pdf': 'https://www.galvbaygrade.org/',
 'RESIN Portal.pdf': 'https://experience.arcgis.com/experience/e9430d121b4b4c07a6589f2bb522e582/page/page_0/?views=view_32',
 'Calwater - Drought Information and Resources.txt': 'https://www.calwater.com/conservation/drought/',
 'Sustainable Cities Network.pdf': 'https://globalfutures.asu.edu/sustainable-cities/',
 'Tribal-Tax-Primer-3.pdf': 'https://azeconcenter.org/wp-content/uploads/2023/12/Tribal-Tax-Primer-3.pdf',
 'GAO- precision farming.pdf': 'https://www.gao.gov/products/gao-24-105962',
 'Precision Agriculture in Crop Production _ NIFA.pdf': 'https://www.nifa.usda.gov/grants/programs/precision-geospatial-sensor-technologies-programs/precision-agriculture-crop-production',
 'howToXeriscape.txt': 'https://wateruseitwisely.com/saving-water-outdoors/how-to-xeriscape/',
 'Make Low-Water Use Plants a High Priority.txt': 'https://wateruseitwisely.com/saving-water-outdoors/how-to-xeriscape/low-water-use-plants/',
 'Water-Saving Tips.txt': 'https://wateruseitwisely.com/saving-water-outdoors/',
 'Planting Trees and Shrubs.txt': 'https://wateruseitwisely.com/saving-water-outdoors/our-top-landscape-ideas/planting-trees-shrubs/',
 'Programming Your Irrigation Controller _ Timer.txt': 'https://wateruseitwisely.com/saving-water-outdoors/our-top-landscape-ideas/programming-your-controller-timer/',
 'Summer Scaping.txt': 'https://wateruseitwisely.com/saving-water-outdoors/our-top-landscape-ideas/summer-scaping/',
 'Sustainable Water Planning.txt': 'https://www.avondaleaz.gov/government/departments/public-works/water/sustainable-water-planning',
 'Summary-of CAGRD-History-and-Operations.pdf': 'https://library.cap-az.com/cagrd/documents/Summary-of%20CAGRD-History-and-Operations.pdf',
 'verde_water_scorecard.pdf': 'https://verderiver.org/learn/watershed-report-card/',
 'Understanding Your Water Bill.txt': 'https://www.epa.gov/watersense/understanding-your-water-bill',
 'WaterSense.txt': 'https://www.epa.gov/watersense/about-watersense',
 'Save with Us.txt': 'https://www.epa.gov/watersense/save-us',
 'StartSaving.txt': 'https://www.epa.gov/watersense/start-saving',
 'Final_AWBA_2022_Annual_Report-10_Year_Plan_with_letter_0.pdf': 'https://waterbank.az.gov/sites/default/files/2023-06/2023.06.30_Final_AWBA_2022_Annual_Report-10_Year_Plan_with_letter_0.pdf',
 'AWBA 2023 Plan of Operation.pdf': 'https://waterbank.az.gov/sites/default/files/2023-01/AWBA%202023%20Plan%20of%20Operation.pdf',
 'AMWUA_coloradoshortage.txt': 'https://www.amwua.org/where-we-stand/issues/colorado-river-structural-deficit',
 'AMWUA_droughtandshortage.txt': 'https://www.amwua.org/where-we-stand/issues/drought-and-shortage',
 'Tier 1 Colorado River Shortage 2024.txt': 'https://www.amwua.org/blog/reclamation-confirms-a-tier-1-colorado-river-shortage-for-2024',
 '2022_cwaa.pdf': 'https://static.azdeq.gov/wqd/wqa/2022_cwaa.pdf',
 'ArizonaPublicSchoolPgm.pdf': 'https://azdeq.gov/node/3634',
 'MyCommunity.txt': 'https://azdeq.gov/MyCommunity',
 'doWeHaveEnough.txt': 'https://www.arizonawaterfacts.com/do-we-have-enough',
 '2021 City of Mesa Water Quality Consumer Confidence Report.pdf': 'https://issuu.com/mesawaterresources/docs/2021_water_quality_report_pdf_doc',
 '2021_Glendale_Hedgepeth_WQR.pdf': 'www.glendaleaz.com/2021ccr',
 '2022_Glendale_Hedgepeth_WQR.pdf': 'www.glendaleaz.com/2022ccr',
 '2022 gilbert water quality.pdf': 'https://www.gilbertaz.gov/home/showpublisheddocument/46853/638248604751470000',
 '2022 tuscon water quality report.pdf': 'https://www.tucsonaz.gov/files/sharedassets/public/v/1/water/documents/wq/mainsystem.pdf',
 '2022 yuma Water Quality Report .pdf': 'https://www.yumaaz.gov/government/utilities/lab-reports/water-quality-report',
 '2022-11-colorado-river-shortage-faq.pdf': 'https://library.cap-az.com/documents/departments/planning/colorado-river-programs/2024-02-colorado-river-shortage-faq.pdf',
 'ADPAR_2023_FINAL.pdf': 'https://www.azwater.gov/sites/default/files/2023-12/ADPAR_2023_FINAL.pdf',
 '2023 scottsdale Water Quality Report.pdf': 'https://www.scottsdaleaz.gov/Assets/ScottsdaleAZ/Water/Water+Quality/2023+Water+Quality+Report.pdf',
 'ArizonaStrategicVisionforWaterResourcesSustainabilityfor thenextcentury_May2014 (17).pdf': 'https://www.azwater.gov/sites/default/files/media/ArizonaStrategicVisionforWaterResourcesSustainability_May2014%20%2817%29.pdf',
 'arizonawaterfacts.txt': 'https://www.arizonawaterfacts.com/water-your-facts',
 'cap-fact-sheet-know-your-water-2022.pdf': 'https://knowyourwaternews.com/wp-content/uploads/2020/12/CAP-Fact-Sheet-Know-Your-Water.pdf',
 'Ch.-5.7-Chemehuevi-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2020/01/Ch.-5.7-Chemehuevi-Current-Future-Water-Use-12-13-2018.pdf',
 'Ch.-5.10-Cocopah-Current-Future-Use-Section-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2020/01/Ch.-5.10-Cocopah-Current-Future-Use-Section-12-13-2018.pdf',
 'Ch.-5.1-Ute-Tribe-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'Ch.-5.2-SUIT-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'Ch.-5.3-UMUT-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'Ch.-5.4-Jicarilla-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'Ch.-5.5-Navajo-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'Ch.-5.6-Ft.-Mojave-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'Ch.-5.8-CRIT-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'Ch.-5.9-Quechan-Current-Future-Water-Use-12-13-2018.pdf': 'https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf',
 'tribal clean water.pdf': 'https://www.naturalresourcespolicy.org/docs/water-tribes/wti-full-report-4.21.pdf',
 'Wastewater Treatment and reclaimed water arizona - focused on flagstaff.PDF': 'https://www.flagstaff.az.gov/DocumentCenter/View/15091/ADEQ_Flagstaff-Reclaimed-Water-Presentation_Final',
 'Title25Ch3.pdf': 'https://www.tolc-nsn.gov/docs/Title25Ch3.pdf',
 'waste water treatment.txt': 'https://wickenburgaz.gov/1434/Water-Wastewater',
 'water sanitation and hygiene.txt': 'https://www.unicef.org/wash#:~:text=Growing%20up%20in%20a%20clean,a%20healthier%20start%20in%20life.',
 'howCanIhelp.txt': 'https://www.arizonawaterfacts.com',
 'mesa_waterquality_2022.pdf': 'https://www.mesaaz.gov/residents/water/water-quality',
 'Rainwater-Harvesting-Leads-to-More-Culturally-Appropriate-Food-in-Water-Scarce-Native-American-Commu.txt': 'https://www.pewtrusts.org/en/research-and-analysis/articles/2023/05/16/rainwater-harvesting-can-increase-access-to-cultural-foods',
 'reclaimed_wastewater.txt': 'https://www.usgs.gov/special-topics/water-science-school/science/reclaimed-wastewater',
 'Tempe_WaterQualityReport2021.pdf': 'https://www.tempe.gov/government/municipal-utilities/water/water-quality/annual-water-reports',
 'Tempe_WaterQualityReport2022.pdf': 'https://www.tempe.gov/government/municipal-utilities/water/water-quality/annual-water-reports',
 'Regain our Water (article).pdf': 'https://ensia.com/features/water-rights-gila-river-indian-community-native-american-american-west/',
 'phx_waterQualityReport.pdf': 'https://www.phoenix.gov/waterservicessite/documents/wsdprimarywqr.pdf',
 'phx_waterquality_2022.pdf': 'https://www.phoenix.gov/waterservicessite/Documents/wsdprimarywqr2022.pdf',
 'phx_waterquality_2021.pdf': 'https://www.phoenix.gov/waterservicessite/Documents/wsdprimarywqr2021.pdf',
 'maricopa county water quality.txt': 'https://www.maricopa.gov/2353/Drinking-Water-Quality',
 'prescot water quality report.pdf': 'https://prescott-az.gov/wp-content/uploads/2023/11/ccr-ry2022.pdf',
 'Restoring_Sacred_Waters_Nania_Guarino2014.pdf': 'https://scholar.law.colorado.edu/cgi/viewcontent.cgi?article=1001&context=books_reports_studies',
 'The Ten Tribes Partnership.pdf': 'https://tentribespartnership.org/',
 'Tohono O’odham Nation.pdf': 'http://www.tonation-nsn.gov/water-resources/',
 'waterBuildsOurEconomy.txt': 'https://www.arizonawaterfacts.com/water-builds-our-economy#:~:text=A%20stable%20secure%20long%2Dterm,efficient%20in%20their%20water%20use.',
 'phx_anthem_2022.pdf': 'https://www.phoenix.gov/waterservicessite/documents/wsdanthemwestwqr.pdf',
 'The pima-maricopa irrigation project nation-building through irrigation infrastructure - Irrigation.txt': 'https://irrigationleadermagazine.com/the-pima-maricopa-irrigation-project/',
 'tribal water security.pdf': 'https://www.epa.gov/system/files/documents/2021-10/2021-ow-tribal-action-plan_508_0.pdf',
 'Universal Access to Clean Water for Tribes in the Colorado River Basin.pdf': 'https://www.naturalresourcespolicy.org/docs/water-tribes/wti-full-report-4.21.pdf',
 'lower-colorado-river-water-quality-partnership-fact-sheet.pdf': 'https://www.mwdh2o.com/media/n4vihp5s/lower_colorado_river_water_quality_partnership_flyer.pdf',
 'interim guidelines for operation of lake powell and lake maed.pdf': 'https://www.usbr.gov/lc/region/programs/strategies/RecordofDecision.pdf',
 'kyl_center_elusive_concept_assured_water_supply.pdf': 'https://morrisoninstitute.asu.edu/sites/default/files/kyl_center_elusive_concept_101619.docx.pdf',
 'Interior Department Welcomes Significant Progress for Indian Water Rights Settlements.pdf': 'https://www.doi.gov/pressreleases/interior-department-welcomes-significant-progress-indian-water-rights-settlements#:~:text=WASHINGTON%20%E2%80%94%20The%20Department%20of%20the,treaty%20responsibilities%20to%20Tribal%20communities.',
 'impacts_of_colorado_river_shortage_to_tap_water_deliveries_in_central_arizona.pdf': 'https://morrisoninstitute.asu.edu/sites/default/files/impacts_of_colorado_river_shortage_to_tap_water_deliveries_in_central_arizona.pdf',
 'Gila river - water settlement.pdf': 'https://www.gilariver.org/index.php/about/water-settlement#:~:text=Since%20before%20the%20arrival%20of,ned%20irrigation%20system%20in%20place.',
 'hard_water_info_az.txt': 'https://www.mesaaz.gov/residents/water/water-quality/hard-water',
 'desalination.txt': 'https://www.usgs.gov/special-topics/water-science-school/science/desalination',
 'current colorado system study.pdf': 'https://www.usbr.gov/lc/region/g4000/24mo.pdf',
 'City-of-Chandler-2022-Water-Quality-Report-June-2023.pdf': 'https://www.chandleraz.gov/residents/water/water-quality',
 'CAP-FactSheet-January2024.pdf': 'https://library.cap-az.com/documents/factsheets/CAP-FactSheet-January2024.pdf',
 'CAP-FactSheet-EconomicImpact-2022.pdf': 'https://library.cap-az.com/documents/factsheets/CAP-FactSheet-EconomicImpact-2022.pdf',
 'CAP-FactSheet-CAGRD-2024.pdf': 'https://knowyourwaternews.com/wp-content/uploads/2024/01/CAP-FactSheet-CAGRD-Jan2024.pdf',
 'CAP-FactSheet-Sustainability.pdf': 'https://library.cap-az.com/documents/factsheets/CAP-FactSheet-Sustainability.pdf',
 'CAP-FactSheet-WaterQuality-2023.pdf': 'https://library.cap-az.com/documents/factsheets/CAP-FactSheet-WaterQuality-2024.pdf',
 'cap-factsheet-power-portfolio.pdf': 'https://www.cap-az.com/water/cap-system/power-operations/',
 'chandler water.txt': 'https://www.chandleraz.gov/residents/water',
 'CAP-FactSheet-ClimateChange-2024.pdf': 'https://knowyourwaternews.com/wp-content/uploads/2020/05/cap-climate-change-fact-sheet.pdf',
 'cap-fact-sheet-shortage-milestones.pdf': 'https://library.cap-az.com/documents/factsheets/cap-fact-sheet-shortage-milestones.pdf',
 'CAP-FactSheet-FederalRepayment-2023.pdf': 'https://knowyourwaternews.com/wp-content/uploads/2021/04/2021-04-Repayment-FactSheet.pdf',
 'FAQ_groundwater permitting and wells.pdf': "https://www.azwater.gov/permitting-wells/frequently-asked-questions#:~:text=How%20can%20I%20locate%20my,on%20your%20county%20assessor's%20website.",
 'Havasupai - Tribal Water Uses in the Colorado River Basin.pdf': 'https://www.tribalwateruse.org/?page_id=189',
 'Hopi - Tribal Water Uses in the Colorado River Basin.pdf': 'https://www.tribalwateruse.org/?page_id=149',
 'arizona_groundwatermanagement.pdf': 'https://www.azwater.gov/ama/active-management-area-overview',
 'the_arizona_dcp_-_a_tribal_perspective.pdf': 'https://aipi.asu.edu/sites/default/files/the_arizona_dcp_-_a_tribal_perspective.pdf',
 'Outdoor Water Use.txt': 'https://www.azwater.gov/conservation/landscaping#:~:text=Landscaping%20%2D%20Residential%20%26%20professional,courses%2C%20sport%20fields%20and%20resorts',
 'sun_corridor_2021_final.pdf': 'https://morrisoninstitute.asu.edu/sites/default/files/sun_corridor_2021_final.pdf',
 "Changes to Arizona's Adjudication & Statutes.pdf": 'https://morrisoninstitute.asu.edu/sites/default/files/lessons_from_the_past_0.pdf',
 'Housing Affordability and Groundwater Regulation.pdf': 'https://morrisoninstitute.asu.edu/sites/default/files/housing_affordability_and_groundwater.pdf',
 'Future of Water in Arizona.txt': 'https://news.asu.edu/20221115-arizona-impact-future-water-arizona',
 'What is ASU doing_.txt': 'https://sustainability-innovation.asu.edu/campus/what-asu-is-doing/#:~:text=ASU%20has%20reduced%20water%20consumption,water%20than%20their%20conventional%20counterparts.',
 'AWII.txt': 'https://azwaterinnovation.asu.edu/',
 'SDG Impact- ASU.txt': 'https://sdgimpact.asu.edu/sdg-6-clean-water-and-sanitation#free-drinking-water',
 'apache-junction_waterQualityReport2022.pdf': 'https://www.azwater.com/files/water-quality/ccr-apache-junction_2022.pdf',
 'Apache Junction water.txt': 'https://www.apachejunctionaz.gov/1091/Water-Resources',
 'Avondale City waterQualityReport.pdf': 'https://www.avondaleaz.gov/home/showpublisheddocument/18226/638211455805300000',
 'Avondale City water.txt': 'https://www.avondaleaz.gov/government/departments/public-works/water',
 '2022Benson WaterQualityReport.pdf': 'https://webgen1files1.revize.com/cityofbensonaz/Document%20Center/Department/Public%20Works/Water/2022%20CCR%20Benson%20Water.pdf',
 '2022WaterQualityReport - Whetstone Ranch.pdf': 'https://webgen1files1.revize.com/cityofbensonaz/Document%20Center/Department/Public%20Works/Water/Consumer%20Confidence%20Report/2022%20Consumer%20Confidence%20Report%20-%20Whetstone%20Ranch.pdf',
 '2022 Water Quality Report- Buckeye.pdf': 'https://www.buckeyeaz.gov/home/showpublisheddocument/12814/638282193806100000',
 'Bullhead City Water Conservation2022.pdf': 'https://www.bullheadcity.com/home/showpublisheddocument/16850/637909053157970000',
 'Billhead City water.txt': 'https://www.bullheadcity.com/government/water-energy-resources',
 'CSWR_FAQ.txt': 'https://www.centralstateswaterresources.com/frequently-asked-questions#card-view/card/67231c7d-2352-4402-953d-9ab614df6e0e_d011cbe3-6a97-4bfb-8cc6-cf4440851dfa',
 'FINAL Williams Water Master Plan.pdf': 'https://cdnsm5-hosted.civiclive.com/UserFiles/Servers/Server_9450682/File/Departments%20and%20Services/Waste&Wastewater/FINAL%20Williams%20Water%20Master%20Plan%20-%20full%20size%20maps.pdf',
 'Willcox_City_info.txt': 'https://willcox.az.gov/departments/utilities',
 'City of Cottonwood Drought and Water Shortage Preparedness Plan.pdf': 'https://cottonwoodaz.gov/DocumentCenter/View/4069/City-of-Cottonwood-Drought-and-Water-Shortage-Preparedness-Plan-2020',
 'City of El Mirage Water Quality and Resources FAQs.txt': 'https://www.elmirageaz.gov/681/Water-Statement-and-FAQ',
 'Colorado River Shortage Status 2023.pdf': 'https://content.civicplus.com/api/assets/5a1a8a07-f9e7-48bf-a287-3ffe580db3fc',
 'Water Resource Management Flagstaff.txt': 'https://flagstaff.az.gov/2258/Water-Resources-Management',
 'EPCOR WATER MANAGEMENT.txt': 'https://www.fountainhillsaz.gov/760/EPCOR-WATER-MANAGEMENT',
 'Storm Water Pollution Tips.pdf': 'https://www.fountainhillsaz.gov/DocumentCenter/View/755/Storm-Water-Pollution-Tips-PDF?bidId=',
 'Storm Water Management.txt': 'https://www.fountainhillsaz.gov/358/Storm-Water-Management',
 'Jerome_CCR2022.pdf': 'https://jerome.az.gov/water-quality-report',
 'Town of Kearny_water.txt': 'https://www.kearnyaz.gov/public-works/pages/water',
 'Lake Havasu Water Savers.txt': 'https://www.kearnyaz.gov/public-works/pages/water',
 '2022Springville_CCR.pdf': 'https://www.springervilleaz.gov/media/Page%20Document/Public%20works/2022-CCRs.pdf',
 'Water-Quality-Report-CityOfStJohn.pdf': 'https://www.sjaz.us/wp-content/uploads/2022/06/Water-Quality-Report-2021.pdf',
 '2022-Water-Quality-Report-starValley.pdf': 'https://starvalleyaz.com/wp-content/uploads/2023/05/2022-Water-Quality-Report.pdf',
 '2022_QC_Water_Quality_Report_Queen_creek.pdf': 'https://www.queencreekaz.gov/home/showpublisheddocument/38216/638235484870300000',
 'WaterDept_Safford.txt': 'https://www.cityofsafford.us/200/Water',
 'Water Quality Report 2022 San Luis.pdf': 'https://www.sanluisaz.gov/DocumentCenter/View/11376/Water-Quality-Report-2022---Web',
 'Water Resource Management_City of Goodyear.txt': 'https://www.goodyearaz.gov/government/departments/water-services/water-resource-management',
 'ccr-Oro Valley.pdf': 'https://www.orovalleyaz.gov/files/assets/public/v/1/documents/water-utility/consumer-confidence-reports/ccr-10-175-2023-cs-final-pdf.pdf',
 '2022-CCR-Page.pdf': 'https://pageutility.com/wp-content/uploads/2023/05/2022-CCR.pdf',
 'Town of Paradise Valley_UtilityServices.txt': 'https://www.paradisevalleyaz.gov/510/Utility-Services',
 'Town of Payson Water Department.txt': 'https://www.paysonaz.gov/departments/water-department',
 'Water Services Strategic Plan_Peoria.pdf': 'https://www.peoriaaz.gov/home/showpublisheddocument/27176/637767962335070000',
 "Governor'sWaterPolicyCouncil.txt" : 'https://www.azwater.gov/gwpc',
 "GWPC_Agenda_Full.pdf":'https://www.azwater.gov/sites/default/files/adwr_meetings_docs/GWPC_Agenda_Full.pdf',
 "wrrc-annual-report-2021.pdf":'https://wrrc.arizona.edu/sites/wrrc.cals.arizona.edu/files/2022-10/wrrc-annual-report-2021.pdf',
  "wrrc-annual-report-2021.pdf" :"https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2023-06/wrrc-2022-annual-report-6-9-23.pdf",
 "asu_morrison_advisory_board_members.txt": "https://morrisoninstitute.asu.edu/about/advisory-board-members",
 "Who’s Who of Arizona Water Issues.txt" : "https://itcaonline.com/programs/tribal-leaders-water-policy-council/whos-who/"}

def LookupWebsource(filename):
    websource = source_dict.get(filename)
    if websource:
        return websource
    else:
        print('File not found')
        return 'File websource not found.'
