source_dict = {
"Pesticide and Groundwater Quality.pdf": "https://azdeq.gov/node/4677",
"the_myth_of_safe-yield_0.pdf": "https://morrisoninstitute.asu.edu/sites/default/files/the_myth_of_safe-yield_0.pdf",
"NAU WaTER Lab.pdf": "http://www.dymondlab.com/research.html",
"Tri-University Water Recharge Collaboration.pdf": "https://ccass.arizona.edu/arizona-tri-university-recharge-and-water-reliability-project",
"Yuma_Factsheet_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Yuma_Factsheet_01_2024.pdf",
"Factsheet_Development_Overview.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-03/Factsheet_Development_Overview.pdf",
"Maricopa_Factsheet_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Maricopa_Factsheet_01_2024.pdf",
"Pima_6-page_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Pima_6-page_01_2024.pdf",
"Cochise_Factsheet_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Cochise_Factsheet_01_2024.pdf",
"Mohave_8-page_01_2024.pdf": "https://wrrc.arizona.edu/publication/arizona-water-factsheet-mohave-county",
"Yavapai_8-page_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Yavapai_8-page_01_2024.pdf",
"Graham_Factsheet_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Graham_Factsheet_01_2024.pdf",
"Greenlee_Factsheet_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Greenlee_Factsheet_01_2024.pdf",
"Gila_Factsheet_01_2024.pdf": "https://wrrc.arizona.edu/publication/arizona-water-factsheet-gila-county",
"La Paz_Factsheet_01_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/La%20Paz_Factsheet_01_2024.pdf",
"Santa Cruz_02.2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-02/Santa%20Cruz_02.2024.pdf",
"Coconino_Factsheet_03_2024.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-03/Coconino_Factsheet_03_2024.pdf",
"Galveston Bay Report Card.pdf": "https://www.galvbaygrade.org/",
"RESIN Portal.pdf": "https://experience.arcgis.com/experience/e9430d121b4b4c07a6589f2bb522e582/page/page_0/?views=view_32",
"Calwater - Drought Information and Resources.pdf": "https://www.calwater.com/conservation/drought/",
"Sustainable Cities Network.pdf": "https://globalfutures.asu.edu/sustainable-cities/",
"Tribal-Tax-Primer-3.pdf": "https://azeconcenter.org/wp-content/uploads/2023/12/Tribal-Tax-Primer-3.pdf",
"GAO- precision farming.pdf": " https://www.gao.gov/assets/d24105962high.pdf",
"Precision Agriculture in Crop Production _ NIFA.pdf": "https://www.nifa.usda.gov/grants/programs/precision-geospatial-sensor-technologies-programs/precision-agriculture-crop-production",
"howToXeriscape.pdf": "https://wateruseitwisely.com/saving-water-outdoors/how-to-xeriscape/",
"Make Low-Water Use Plants a High Priority.pdf": "https://wateruseitwisely.com/saving-water-outdoors/how-to-xeriscape/low-water-use-plants/",
"Water-Saving Tips.pdf": "https://wateruseitwisely.com/saving-water-outdoors/",
"Planting Trees and Shrubs.pdf": "https://wateruseitwisely.com/saving-water-outdoors/our-top-landscape-ideas/planting-trees-shrubs/",
"Programming Your Irrigation Controller _ Timer.pdf": "https://wateruseitwisely.com/saving-water-outdoors/our-top-landscape-ideas/programming-your-controller-timer/",
"Summer Scaping.pdf": "https://wateruseitwisely.com/saving-water-outdoors/our-top-landscape-ideas/summer-scaping/",
"Sustainable Water Planning.pdf": "https://www.avondaleaz.gov/government/departments/public-works/water/sustainable-water-planning",
"Summary-of CAGRD-History-and-Operations.pdf": "https://library.cap-az.com/cagrd/documents/Summary-of%20CAGRD-History-and-Operations.pdf",
"verde_water_scorecard.pdf": "https://verderiver.org/learn/watershed-report-card/",
"Understanding Your Water Bill.pdf": "https://www.epa.gov/watersense/understanding-your-water-bill",
"WaterSense.pdf": "https://www.epa.gov/watersense/about-watersense",
"Save with Us.pdf": "https://www.epa.gov/watersense/save-us",
"StartSaving.pdf": "https://www.epa.gov/watersense/start-saving",
"Final_AWBA_2022_Annual_Report-10_Year_Plan_with_letter_0.pdf": "https://waterbank.az.gov/sites/default/files/2023-06/2023.06.30_Final_AWBA_2022_Annual_Report-10_Year_Plan_with_letter_0.pdf",
"AWBA 2023 Plan of Operation.pdf": "https://waterbank.az.gov/sites/default/files/2023-01/AWBA%202023%20Plan%20of%20Operation.pdf",
"AMWUA_coloradoshortage.pdf": "https://www.amwua.org/where-we-stand/issues/colorado-river-structural-deficit",
"AMWUA_droughtandshortage.pdf": "https://www.amwua.org/where-we-stand/issues/drought-and-shortage",
"Tier 1 Colorado River Shortage 2024.pdf": "https://www.amwua.org/blog/reclamation-confirms-a-tier-1-colorado-river-shortage-for-2024",
"2022_cwaa.pdf": "https://static.azdeq.gov/wqd/wqa/2022_cwaa.pdf",
"ArizonaPublicSchoolPgm.pdf": "https://azdeq.gov/node/3634",
"MyCommunity.pdf": "https://azdeq.gov/MyCommunity",
"doWeHaveEnough.pdf": "https://www.arizonawaterfacts.com/do-we-have-enough",
"Water Quality Report-1.pdf": "https://issuu.com/mesawaterresources/docs/2021_water_quality_report_pdf_doc",
"2021_Glendale_Hedgepeth_WQR.pdf": "www.glendaleaz.com/2021ccr",
"2022 gilbert water quality.pdf": "https://www.gilbertaz.gov/home/showpublisheddocument/46853/638248604751470000",
"2022 tuscon water quality report.pdf": "https://www.tucsonaz.gov/files/sharedassets/public/v/1/water/documents/wq/mainsystem.pdf",
"Water Quality Report-2.pdf": "https://www.yumaaz.gov/government/utilities/lab-reports/water-quality-report",
"2022-11-colorado-river-shortage-faq.pdf": "https://library.cap-az.com/documents/departments/planning/colorado-river-programs/2024-02-colorado-river-shortage-faq.pdf",
"ADPAR_2023_FINAL.pdf": "https://www.azwater.gov/sites/default/files/2023-12/ADPAR_2023_FINAL.pdf",
"2023 scottsdale Water Quality Report.pdf": "https://www.scottsdaleaz.gov/Assets/ScottsdaleAZ/Water/Water+Quality/2023+Water+Quality+Report.pdf",
"ArizonaStrategicVisionforWaterResourcesSustainabilityfor thenextcentury_May2014 (17).pdf": "https://www.azwater.gov/sites/default/files/media/ArizonaStrategicVisionforWaterResourcesSustainability_May2014%20%2817%29.pdf",
"arizonawaterfacts.pdf": "https://www.arizonawaterfacts.com/water-your-facts",
"cap-fact-sheet-know-your-water-2022.pdf": "https://knowyourwaternews.com/wp-content/uploads/2020/12/CAP-Fact-Sheet-Know-Your-Water.pdf",
"Ch.-5.7-Chemehuevi-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2020/01/Ch.-5.7-Chemehuevi-Current-Future-Water-Use-12-13-2018.pdf",
"Ch.-5.10-Cocopah-Current-Future-Use-Section-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2020/01/Ch.-5.10-Cocopah-Current-Future-Use-Section-12-13-2018.pdf",
"Ch.-5.1-Ute-Tribe-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"Ch.-5.2-SUIT-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"Ch.-5.3-UMUT-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"Ch.-5.4-Jicarilla-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"Ch.-5.5-Navajo-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"Ch.-5.6-Ft.-Mojave-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"Ch.-5.8-CRIT-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"Ch.-5.9-Quechan-Current-Future-Water-Use-12-13-2018.pdf": "https://tentribespartnership.org/wp-content/uploads/2019/12/WaterStudy.pdf",
"tribal clean water.pdf": "https://www.naturalresourcespolicy.org/docs/water-tribes/wti-full-report-4.21.pdf",
"Wastewater Treatment and reclaimed water arizona - focused on flagstaff.PDF": "https://www.flagstaff.az.gov/DocumentCenter/View/15091/ADEQ_Flagstaff-Reclaimed-Water-Presentation_Final",
"Title25Ch3.pdf": "https://www.tolc-nsn.gov/docs/Title25Ch3.pdf",
"waste water treatment.pdf": "https://www.wickenburgaz.gov/DocumentCenter/View/2273/General-Plan-2025",
"water sanitation and hygiene.pdf": "https://www.unicef.org/wash#:~:text=Growing%20up%20in%20a%20clean,a%20healthier%20start%20in%20life.",
"howCanIhelp.pdf": "https://www.arizonawaterfacts.com",
"mesa_waterquality_2022.pdf": "https://www.mesaaz.gov/residents/water/water-quality",
"Rainwater-Harvesting-Leads-to-More-Culturally-Appropriate-Food-in-Water-Scarce-Native-American-Commu.pdf": "https://ashiwi.org/POZUtility.htm",
"reclaimed_wastewater.pdf": "https://www.usgs.gov/special-topics/water-science-school/science/reclaimed-wastewater",
"Regain our Water (article).pdf": "https://ensia.com/features/water-rights-gila-river-indian-community-native-american-american-west/",
"phx_waterQualityReport.pdf": "https://www.phoenix.gov/waterservicessite/documents/wsdprimarywqr.pdf",
"Water Quality Report 2022-3.pdf": "https://www.phoenix.gov/waterservicessite/Documents/wsdprimarywqr2022.pdf",
"phx_waterquality_2021.pdf": "https://www.phoenix.gov/waterservicessite/Documents/wsdprimarywqr2021.pdf",
"maricopa county water quality.pdf": "https://www.maricopa.gov/2353/Drinking-Water-Quality",
"prescot water quality report.pdf": "https://prescott-az.gov/wp-content/uploads/2023/11/ccr-ry2022.pdf",
"Restoring_Sacred_Waters_Nania_Guarino2014.pdf": "https://scholar.law.colorado.edu/cgi/viewcontent.cgi?article=1001&context=books_reports_studies",
"The Ten Tribes Partnership.pdf": "https://tentribespartnership.org/",
"Tohono O'odham Nation.pdf": "http://www.tonation-nsn.gov/water-resources/",
"waterBuildsOurEconomy.pdf": "https://www.arizonawaterfacts.com/water-builds-our-economy#:~:text=A%20stable%20secure%20long%2Dterm,efficient%20in%20their%20water%20use.",
"phx_anthem_2022.pdf": "https://www.phoenix.gov/waterservicessite/documents/wsdanthemwestwqr.pdf",
"The pima-maricopa irrigation project nation-building through irrigation infrastructure - Irrigation.pdf": "https://irrigationleadermagazine.com/the-pima-maricopa-irrigation-project/",
"tribal water security.pdf": "https://www.epa.gov/system/files/documents/2021-10/2021-ow-tribal-action-plan_508_0.pdf",
"Universal Access to Clean Water for Tribes in the Colorado River Basin.pdf": "https://www.naturalresourcespolicy.org/docs/water-tribes/wti-full-report-4.21.pdf",
"lower-colorado-river-water-quality-partnership-fact-sheet.pdf": "https://www.mwdh2o.com/media/n4vihp5s/lower_colorado_river_water_quality_partnership_flyer.pdf",
"interim guidelines for operation of lake powell and lake maed.pdf": "https://www.usbr.gov/lc/region/programs/strategies/RecordofDecision.pdf",
"kyl_center_elusive_concept_assured_water_supply.pdf": "https://morrisoninstitute.asu.edu/sites/default/files/kyl_center_elusive_concept_101619.docx.pdf",  
"Interior Department Welcomes Significant Progress for Indian Water Rights Settlements.pdf": "https://www.doi.gov/pressreleases/interior-department-welcomes-significant-progress-indian-water-rights-settlements#:~:text=WASHINGTON%20%E2%80%94%20The%20Department%20of%20the,treaty%20responsibilities%20to%20Tribal%20communities.",
"impacts_of_colorado_river_shortage_to_tap_water_deliveries_in_central_arizona.pdf": "https://morrisoninstitute.asu.edu/sites/default/files/impacts_of_colorado_river_shortage_to_tap_water_deliveries_in_central_arizona.pdf",
"Gila river - water settlement.pdf": "https://www.gilariver.org/index.php/about/water-settlement#:~:text=Since%20before%20the%20arrival%20of,ned%20irrigation%20system%20in%20place.",
"hard_water_info_az.pdf": "https://www.mesaaz.gov/residents/water/water-quality/hard-water",
"desalination.pdf": "https://www.usgs.gov/special-topics/water-science-school/science/desalination",
"current colorado system study.pdf": "https://www.usbr.gov/lc/region/g4000/24mo.pdf",
"City-of-Chandler-2022-Water-Quality-Report-June-2023.pdf": "https://www.chandleraz.gov/sites/default/files/documents/imported/ChandlerGeneralPlan2016.pdf",
"CAP-FactSheet-January2024.pdf": "https://library.cap-az.com/documents/factsheets/CAP-FactSheet-January2024.pdf",
"CAP-FactSheet-EconomicImpact-2022.pdf": "https://library.cap-az.com/documents/factsheets/CAP-FactSheet-EconomicImpact-2022.pdf",
"CAP-FactSheet-CAGRD-2024.pdf": "https://knowyourwaternews.com/wp-content/uploads/2024/01/CAP-FactSheet-CAGRD-Jan2024.pdf",
"CAP-FactSheet-Sustainability.pdf": "https://library.cap-az.com/documents/factsheets/CAP-FactSheet-Sustainability.pdf",
"CAP-FactSheet-WaterQuality-2023.pdf": "https://library.cap-az.com/documents/factsheets/CAP-FactSheet-WaterQuality-2024.pdf",
"cap-factsheet-power-portfolio.pdf": "https://www.cap-az.com/water/cap-system/power-operations/",
"Water-1.pdf": "https://www.chandleraz.gov/residents/water",
"CAP-FactSheet-ClimateChange-2024.pdf": "https://knowyourwaternews.com/wp-content/uploads/2020/05/cap-climate-change-fact-sheet.pdf",
"cap-fact-sheet-shortage-milestones.pdf": "https://library.cap-az.com/documents/factsheets/cap-fact-sheet-shortage-milestones.pdf",
"CAP-FactSheet-FederalRepayment-2023.pdf": "https://knowyourwaternews.com/wp-content/uploads/2021/04/2021-04-Repayment-FactSheet.pdf",
"FAQ_groundwater permitting and wells.pdf": "https://www.azwater.gov/permitting-wells/frequently-asked-questions#:~:text=How%20can%20I%20locate%20my,on%20your%20county%20assessor's%20website.",
"Havasupai - Tribal Water Uses in the Colorado River Basin.pdf": "https://www.tribalwateruse.org/?page_id=189",
"Hopi - Tribal Water Uses in the Colorado River Basin.pdf": "https://www.tribalwateruse.org/?page_id=149",
"arizona_groundwatermanagement.pdf": "https://www.azwater.gov/ama/active-management-area-overview",
"the_arizona_dcp_-_a_tribal_perspective.pdf": "https://aipi.asu.edu/sites/default/files/the_arizona_dcp_-_a_tribal_perspective.pdf",
"Outdoor Water Use.pdf": "https://www.azwater.gov/conservation/landscaping#:~:text=Landscaping%20%2D%20Residential%20%26%20professional,courses%2C%20sport%20fields%20and%20resorts",
"sun_corridor_2021_final.pdf": "https://morrisoninstitute.asu.edu/sites/default/files/sun_corridor_2021_final.pdf",
"Changes to Arizona's Adjudication & Statutes.pdf": "https://morrisoninstitute.asu.edu/sites/default/files/lessons_from_the_past_0.pdf",
"Housing Affordability and Groundwater Regulation.pdf": "https://morrisoninstitute.asu.edu/sites/default/files/housing_affordability_and_groundwater.pdf",  
"Future of Water in Arizona.pdf": "https://news.asu.edu/20221115-arizona-impact-future-water-arizona",
"What is ASU doing_.pdf": "https://sustainability-innovation.asu.edu/campus/what-asu-is-doing/#:~:text=ASU%20has%20reduced%20water%20consumption,water%20than%20their%20conventional%20counterparts.",
"AWII.pdf": "https://azwaterinnovation.asu.edu/",
"SDG Impact- ASU.pdf": "https://sdgimpact.asu.edu/sdg-6-clean-water-and-sanitation#free-drinking-water",
"apache-junction_waterQualityReport2022.pdf": "https://www.azwater.com/files/water-quality/ccr-apache-junction_2022.pdf",
"Apache Junction water.pdf": "https://www.apachejunctionaz.gov/1091/Water-Resources",
"Avondale City waterQualityReport.pdf": "https://www.avondaleaz.gov/home/showpublisheddocument/18226/638211455805300000",
"Avondale City water.pdf": "https://ehq-production-us-california.s3.us-west-1.amazonaws.com/b3c2e5d8bddb0497ce8904344e508a3799114be9/original/1703787282/60caadf187c5e35812ede861f2143373_RES_1080-1223_-_Recorded.pdf",
"2022Benson WaterQualityReport.pdf": "https://webgen1files1.revize.com/cityofbensonaz/Document%20Center/Department/Public%20Works/Water/2022%20CCR%20Benson%20Water.pdf",
"2022WaterQualityReport - Whetstone Ranch.pdf": "https://webgen1files1.revize.com/cityofbensonaz/Document%20Center/Department/Public%20Works/Water/Consumer%20Confidence%20Report/2022%20Consumer%20Confidence%20Report%20-%20Whetstone%20Ranch.pdf",
"2022 Water Quality Report- Buckeye.pdf": "https://www.buckeyeaz.gov/home/showpublisheddocument/12814/638282193806100000",
"Bullhead City Water Conservation2022.pdf": "https://www.bullheadcity.com/home/showpublisheddocument/16850/637909053157970000",
"Billhead City water.pdf": "https://www.bullheadcity.com/home/showpublisheddocument/6109/635991581053900000",
"CSWR_FAQ.pdf": "https://www.centralstateswaterresources.com/frequently-asked-questions#card-view/card/67231c7d-2352-4402-953d-9ab614df6e0e_d011cbe3-6a97-4bfb-8cc6-cf4440851dfa",
"FINAL Williams Water Master Plan.pdf": "https://cdnsm5-hosted.civiclive.com/UserFiles/Servers/Server_9450682/File/Departments%20and%20Services/Waste&Wastewater/FINAL%20Williams%20Water%20Master%20Plan%20-%20full%20size%20maps.pdf",
"Willcox_City_info.pdf": "https://willcox.az.gov/media/Planning%20and%20Zoning%20Commission/2040%20General%20Plan.pdf",
"City of Cottonwood Drought and Water Shortage Preparedness Plan.pdf": "https://cottonwoodaz.gov/DocumentCenter/View/4069/City-of-Cottonwood-Drought-and-Water-Shortage-Preparedness-Plan-2020",
"City of El Mirage Water Quality and Resources FAQs.pdf": "https://www.elmirageaz.gov/681/Water-Statement-and-FAQ",
"Colorado River Shortage Status 2023.pdf": "https://content.civicplus.com/api/assets/5a1a8a07-f9e7-48bf-a287-3ffe580db3fc",
"Water Resource Management Flagstaff.pdf": "https://flagstaff.az.gov/2258/Water-Resources-Management",
"EPCOR WATER MANAGEMENT.pdf": "https://www.fountainhillsaz.gov/760/EPCOR-WATER-MANAGEMENT",
"Storm Water Pollution Tips.pdf": "https://www.fountainhillsaz.gov/DocumentCenter/View/755/Storm-Water-Pollution-Tips-PDF?bidId=",
"Storm Water Management.pdf": "https://www.fountainhillsaz.gov/358/Storm-Water-Management",
"Jerome_CCR2022.pdf": "https://jerome.az.gov/documents/76/2018_GENERAL_PLAN_FINAL_reduced.pdf",
"Town of Kearny_water.pdf": "https://www.kearnyaz.gov/sites/g/files/vyhlif7746/f/uploads/conserveplan.pdf",
"Lake Havasu Water Savers.pdf": "https://www.lhcaz.gov/docs/default-source/department-documents/waterconservationplan.pdf?sfvrsn=ad2b2f7c_28",
"2022Springville_CCR.pdf": "https://www.springervilleaz.gov/media/Page%20Document/Public%20works/2022-CCRs.pdf",
"Water-Quality-Report-CityOfStJohn.pdf": "https://www.sjaz.us/wp-content/uploads/2022/06/Water-Quality-Report-2021.pdf",
"Water Quality Report 2022-5.pdf": "https://starvalleyaz.com/wp-content/uploads/2023/05/2022-Water-Quality-Report.pdf",
"2022_QC_Water_Quality_Report_Queen_creek.pdf": "https://www.queencreekaz.gov/home/showpublisheddocument/38869/638422055428170000",
"Water-3.pdf": "https://www.cityofsafford.us/200/Water",
"Water Quality Report 2022-4.pdf": "https://www.sanluisaz.gov/DocumentCenter/View/11376/Water-Quality-Report-2022---Web",
"Water Resource Management_City of Goodyear.pdf": "https://www.goodyearaz.gov/government/departments/water-services/water-resource-management",
"ccr-Oro Valley.pdf": "https://www.orovalleyaz.gov/files/assets/public/v/1/documents/water-utility/consumer-confidence-reports/ccr-10-175-2023-cs-final-pdf.pdf",
"2022-CCR-Page.pdf": "https://pageutility.com/wp-content/uploads/2023/05/2022-CCR.pdf",
"Town of Paradise Valley_UtilityServices.pdf": "https://www.paradisevalleyaz.gov/DocumentCenter/View/9907/6-Environmental-Planning-_-Water-Resources?bidId=",
"Town of Payson Water Department.pdf": "https://www.paysonaz.gov/departments/water-department",
"Water Services Strategic Plan_Peoria.pdf": "https://www.peoriaaz.gov/home/showpublisheddocument/27176/637767962335070000",
"Drought.pdf": "https://new.azwater.gov/drought/faq",
"AMAs.pdf": "https://new.azwater.gov/sites/default/files/media/AMAFACTSHEET2016%20%281%29_0.pdf",
"CAGRD.pdf": "https://www.amwua.org/blog/lets-talk-about-the-cagrd",
"Outdoor Water Use-2.pdf": "https://www.amwua.org/blog/how-to-be-efficient-and-effective-with-your-outdoor-watering",
"Sustainable Cities Network Greater Phoenix Green Infrastructure Handbook.pdf": "https://cdn.globalfutures.asu.edu/sustainable-cities/wp-content/uploads/sites/17/2023/09/LID2018-HandBook-04-11-19.pdf",
"University of Arizona-4.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Mohave_8-page_01_2024.pdf",
"University of Arizona-8.pdf": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2024-01/Gila_Factsheet_01_2024.pdf",
"Water Resources-2.pdf": "https://cottonwoodaz.gov/482/Water-Resources",
"City of El Mirage Water Quality & Resources.pdf": "https://www.elmirageaz.gov/317/Water-Quality-Resources",
"Mojave Water Agency.pdf": "https://www.mojavewater.org/about-mwa/strategic-plan/",
"Brief History of Water Resources.pdf": "http://www.tonation-nsn.gov/water-resources/brief-history/",
"Tribal Water Study Report.pdf": "https://www.usbr.gov/lc/region/programs/crbstudy/tribalwaterstudy.html",
"OVERVIEW OF THE ARIZONA GROUNDWATER MANAGEMENT CODE.pdf": "https://www.azwater.gov/sites/default/files/media/Arizona%20Groundwater_Code_1.pdf",
"Fort Mojave Indian Tribe.pdf": "https://mojaveindiantribe.com/",
"Ak-Chin Indian Community.pdf": "https://www.tribalwateruse.org/?page_id=153",
"Town of Eloy Water Division.pdf": "https://eloyaz.gov/DocumentCenter/View/4933/36-Environmental-Planning-Element",
"USGS.pdf": "https://www.gilabendaz.org/DocumentCenter/View/1154/240327_Final-Existing-Conditions-Report",
"Fort Mojave Indian Tribe-2.pdf": "https://tentribespartnership.org/wp-content/uploads/2020/01/Ch.-5.6-Ft.-Mojave-Current-Future-Water-Use-12-13-2018.pdf", 
"Water Division - City of Benson.pdf": "https://webgen1files1.revize.com/cityofbensonaz/Document%20Center/Department/Planning%20and%20Zoning/General%20Plan/2015_Final_Draft.pdf",
"Water Resources - City of Buckeye.pdf": "https://www.buckeyeaz.gov/home/showpublisheddocument/6300/637928096311900000",
"Resource Information.pdf": "https://www.campverde.az.gov/home/showpublisheddocument/30/638005663542270000",
"Water Quality - Arizona Water Company.pdf": "https://drive.google.com/file/d/1fscThmzMiYY4VO_BT_k29pf47MK6bAaa/view?usp=sharing",
"City of Douglas Water & Sewer.pdf": "https://www.azwater.gov/faqs-douglas-ama",
"Oro Valley Water Utility.pdf": "https://www.orovalleyaz.gov/files/assets/public/v/1/documents/water-utility/standards-specifications-and-checklists/2018_potable_water_master_plan_final.pdf",
"Page Water Department.pdf": "https://cityofpage.org/wp-content/uploads/2023/05/COP_-_2040_General_Plan_Complete_3-1-23.pdf",
"Peoria Water Services.pdf": "https://www.peoriaaz.gov/home/showpublisheddocument/23968/637503575384170000",
"Public Works-2.pdf": "https://www.springervilleaz.gov/media/Page%20Document/Economic%20Development/General-Plan-2015-2025.pdf",
"City of Tempe Water Conservation.pdf": "https://www.tempe.gov/home/showpublisheddocument/101702/638288312294400000",
"Houston Advanced Research Center.pdf": "https://www.austintexas.gov/sites/default/files/files/Water/Water%20Conservation/2024%20DCP%20Final.pdf",
"Groundwater Quality in Arizona 1995-2015": "https://static.azdeq.gov/wqd/gw/fs/16-02_20year_final_ofr.pdf",
"Glossary of Terms": "https://legacy.azdeq.gov/function/help/glossary_drupal.html",
"Recycled Water": "https://azdeq.gov/recycled-water",
"Arizona Department of Environmental Quality Recycled Water Work Groups Final Report": "https://static.azdeq.gov/wqd/combined_workgroup_final_report.pdf",  
"Arizona Drought Preparedness Report 2023": "https://www.azwater.gov/sites/default/files/2023-12/ADPAR_2023_FINAL.pdf",
"Conservation: Agriculture": "https://www.azwater.gov/conservation/agriculture",
"Phoenix Fifth Active Management Plan": "https://www.azwater.gov/sites/default/files/media/Phx5MP.pdf",
"Pinal Fifth Active Management Plan": "https://www.azwater.gov/sites/default/files/media/PAMA5MP.pdf",
"Prescott Fifth Active Management Plan": "https://www.azwater.gov/sites/default/files/media/PrAMA5MP.pdf",
"Santa Cruz Fifth Active Management Plan": "https://www.azwater.gov/sites/default/files/media/SCAMA5MP.pdf",
"Tucson Fifth Active Management Plan": "https://www.azwater.gov/sites/default/files/media/TAMA5MP.pdf",
"Community Water Systems FAQs": "https://www.azwater.gov/cws/cws-frequently-asked-questions",
"Hardest Working River": "https://storymaps.arcgis.com/stories/2efeafc8613440dba5b56cb83cd790ba/print",
"California's Water Supply Strategy": "https://resources.ca.gov/-/media/CNRA-Website/Files/Initiatives/Water-Resilience/CA-Water-Supply-Strategy.pdf",      
"Calwater": "https://drought.calwater.com/faqs",
"Colorado River Shortage FAQ": "https://library.cap-az.com/documents/departments/planning/colorado-river-programs/2024-02-colorado-river-shortage-faq.pdf", 
"CAWCD Property Taxes": "https://library.cap-az.com/documents/departments/finance/CAP-Doc-CAWCDPropertyTaxesQA-121621.pdf",
"Items that Directly Affect the Price of Water in Carefree": "https://carefreewaterco.com/documents/1621/Items_that_Affect_the_Price_of_Water_in_Carefree.pdf",
"Water Resources | Chino Valley, AZ": "https://www.chinoaz.net/176/Water-Resources",
"Drought Contingency Plan": "https://www.austintexas.gov/sites/default/files/files/Water/Water%20Conservation/2024%20DCP%20Final.pdf",
"Tribal Water Uses in Colorado River Basin": "http://www.tribalwateruse.org/?page_id=101",
"University of Colorado Boulder": "https://wwa.colorado.edu/resources/intermountain-west-climate-dashboard/briefing/water-year-2021-summary",
"General Plan - Water Resources": "https://www.coolidgeaz.com/vertical/sites/%7BAE188E70-DD7F-47BE-99EF-B58B70641DF9%7D/uploads/Chapter_7-Water_Resources_06192014.pdf",
"Small Community Environmental Protection Plan": "https://www.eagaraz.gov/media/491",
"CCRs": "https://www.epa.gov/sites/default/files/2018-02/documents/epa-ogwdw-ccr-infographic-v5_508.pdf",
"General Plan - Water Resources-2": "https://flagstaff.az.gov/DocumentCenter/View/41532/VIII---Water-Resources-021113?bidId=",
"Town of Florence Water Resources": "https://www.florenceaz.gov/water-resource/",
"Water Settlement": "https://www.gilariver.org/index.php/about/water-settlement",
"Regain our Water": "https://waterdesk.org/2021/11/a-generational-historic-struggle-to-regain-our-water/",
"Water Rights": "https://ensia.com/features/water-rights-gila-river-indian-community-native-american-american-west",
"Gilbert Water Supply": "https://www.gilbertaz.gov/departments/public-works/water/water-resources/water-supply",
"Glendale Your Water": "https://www.glendaleaz.com/live/city_services/water_services/your_water",
"Arizona Water Company (Fact Sheet)": "https://www.globeaz.gov/sites/g/files/vyhlif5376/f/uploads/fact-sheet.pdf",
"GWPC Executive Order": "https://azgovernor.gov/sites/default/files/eo4.pdf",
"Stormwater Management Plan": "https://www.guadalupeaz.org/sites/g/files/vyhlif6711/f/uploads/stormwater_management_program_swmp_2024.pdf",
"Tribal Water Uses in Colorado River Basin-2": "http://www.tribalwateruse.org/?page_id=189",
"Water Rate Study": "https://townofhaydenaz.gov/wp-content/uploads/2024/04/23_Water_Rate_Study.pdf",
"Tribal Water Uses in Colorado River Basin-3": "http://www.tribalwateruse.org/?page_id=149",
"City Code (Water Conservation)": "https://www.codepublishing.com/AZ/HuachucaCity/#!/html/HuachucaCity13/HuachucaCity1355.html",
"DOI Water Rights Settlement": "https://www.doi.gov/pressreleases/interior-department-welcomes-significant-progress-indian-water-rights-settlements",       
"Tribal Water Uses in Colorado River Basin-4": "http://www.tribalwateruse.org/?page_id=198",
"Colorado River Shortage Story Map": "https://storymaps.arcgis.com/stories/a1a782ce054d4ad28a0d7d0845e6c03d",
"Arizona's Water Story": "https://asu.maps.arcgis.com/apps/Cascade/index.html?appid=a44299ef542a479d8a63b72c348dd1ba",
"Big Picture": "https://storymaps.arcgis.com/stories/0f244e635ef5479394d3eefc81032a79",
"Arizona's Stream Adjudications": "https://storymaps.arcgis.com/stories/48e6754b99a74d398783b732c6254aeb",
"Colorado River Basin Coal Facility": "https://storymaps.arcgis.com/stories/1ad192703c79442b94328f24e5bb6510/print",
"Long-term Storage Credits": "https://storymaps.arcgis.com/stories/61c95c2245e549fbb51fb94e7e0070bb",
"Water and Land Use in Central Arizona": "https://storymaps.arcgis.com/stories/eb51183c1305428187c699d004cbf77b",
"Public Works": "https://townofmammoth.us/public-works-2/",
"Marana Water FAQs": "https://www.maranaaz.gov/water-faq",
"Maricopa Water Resource Element": "https://www.maricopa-az.gov/departments/development-services/planning-maricopa-general-plan/general-plan-elements/public-buildings-facilities-services-element",
"City of Mesa Water FAQs": "https://www.mesaaz.gov/residents/water/water-resources-faqs",
"Flood Damage Prevention Regulations": "https://miamiaz.gov/wp-content/uploads/2022/10/Title-15-Buildings-and-Construction-11-2021-1.pdf",
"Water Rights and Water Use of Coal Facilities": "https://morrisoninstitute.asu.edu/sites/default/files/asu-kc-coalrprt-nov22.pdf",
"Toward a Sense of the Basin": "https://www.naturalresourcespolicy.org/docs/colorado-river-basin/basin-report-2020.pdf",
"Tri-University Water Recharge Collaboration": "https://news.nau.edu/got-water-nau-researchers-a-part-of-a-tri-university-collaboration-to-enhance-water-recharge-in-arizona/",
"Department of Water Resources": "https://nndwr.navajo-nsn.gov/",
"Nogales Water": "https://nogalesaz.gov/wp-content/uploads/2020/12/City_of_Nogales_Stormwater_Management_Plan.pdf",
"Guidance Framework for Direct Potable Reuse in Arizona": "https://www.nwri-usa.org/_files/ugd/632dc3_0bd8e67cef55446f8c3f7759a37512ce.pdf?index=true",     
"Water Quality Control Plan": "http://paiutewater.us/WQS%20Jan%202019.pdf",
"Water management innovation": "https://knowyourwaternews.com/pascua-yaqui-tribe-thrives-on-water-management-innovation/",
"NAU Water-Energy Nexus Study": "http://www.waterenergy.nau.edu/patagonia.html",
"Patagonia": "https://patagonia-az.gov/wp-content/uploads/2011/07/Patagonia-Town-Code-Ch12-w-amendments-from-2012-1.pdf",
"City of Phoenix Water Conservation": "https://www.phoenix.gov/waterservices/resourcesconservation/faqs",
"City of Phoenix Drinking Water": "https://www.phoenix.gov/waterservices/envservices/drinking-water/faqs",
"Irrigation project": "https://irrigationleadermagazine.com/the-pima-maricopa-irrigation-project/",
"A Vision Statement for P-MIP": "https://www.gilariver.com/new-vision.html",
"ADWR": "https://www.pinetoplakesideaz.gov/DocumentCenter/View/855/2015-General-Plan---",
"Pinetop Water": "https://www.pinetopwatercfd.com/conservation-tips",
"Pinetop Water-2": "https://www.pinetopwatercfd.com/documents/581/res2007-2.pdf",
"Water Resources-3": "https://planprescott.com/wp-content/uploads/2023/01/10-Water-Resources-Element.pdf",
"Backflow Code": "https://cms8.revize.com/revize/quartzsite/Document_Center/Department/Utility/Backflow%20Code.pdf",
"Tribal Water Uses in Colorado River Basin-5": "http://www.tribalwateruse.org/?page_id=123",
"FAQs": "https://rippleeffectsedona.com/faqs/",
"General Plan": "https://www.sierravistaaz.gov/home/showpublisheddocument/3356/637876863574970000",
"Conservation Plan": "https://www.snowflakeaz.gov/departments/public-works/water-division/conservation-plan/",
"Flood Irrigation": "https://www.srpnet.com/grid-water-management/water-management/how-irrigation-works",
"PUBLIC WORKS (WATER AND SEWER)": "https://www.sjaz.us/public-works-water-and-sewer/",
"Water Department": "https://starvalleyaz.com/waterdepartment/",
"Water Resource Management": "https://surpriseaz.gov/603/Water-Resource-Management",
"General Plan - Water Resources-3.pdf": "https://content.civicplus.com/api/assets/92746936-baf3-4b14-a50e-204c418083da?cache=1800",
"Tribal Water Uses in Colorado River Basin-2.pdf": "http://www.tribalwateruse.org/?page_id=189",
"Brief History of Tohono O'odham Water": "http://www.tonation-nsn.gov/water-resources/brief-history/",
"Tribal Water Study Overview": "https://www.waterandtribes.org/_files/ugd/1c5bb7_ee6dd174b3524eac82c750300c8ba139.pdf",
"Inventory in the Colorado River Basin": "https://www.tribalwateruse.org/?page_id=569",
"Tucson One Water": "https://tucsononewater.com/wp-content/uploads/2024/04/Tucson_Water_One_Water_2100_Plan_Print_Ready-1.pdf",
"Tucson Water": "https://www.tucsonaz.gov/Departments/Water",
"Tucson One Water-2": "https://tucsononewater.com/wp-content/uploads/2024/04/Tucson_Water_One_Water_2100_Plan_Print_Ready-1.pdf",
"A Common Vision": "https://www.waterandtribes.org/_files/ugd/17c3c8_f1d896681b9c488f86bd2a34754d7e5d.pdf",
"Developing the Next Framework": "https://www.waterandtribes.org/_files/ugd/1c5bb7_c6557dd8e23c4c5d848590e7d36efe96.pdf",
"Status of Tribal Water Rights": "https://www.waterandtribes.org/_files/ugd/17c3c8_1fa6790c664842249959f156b927d10d.pdf",
"The Enduring Role": "https://www.waterandtribes.org/_files/ugd/17c3c8_7705fac3008e4bdf806e268271d187e2.pdf",
"Water and Tribes Initiative": "https://www.waterandtribes.org/",
"Developing the Next Framework-1": "https://www.waterandtribes.org/_files/ugd/1c5bb7_c6557dd8e23c4c5d848590e7d36efe96.pdf",
"Status of Tribal Water Rights-1": "https://www.waterandtribes.org/_files/ugd/17c3c8_1fa6790c664842249959f156b927d10d.pdf",
"Pinal Active Management Area": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/2023-02/final_june-12-2020_wrrc_pinal_ama_water_report.pdf",
"Desert Flows Methodology": "https://wrrc.arizona.edu/sites/wrrc.arizona.edu/files/attachment/Desert%2520Flows%2520Methodology%2520Guidebook_2017.pdf",     
"Water Advisory Committee": "https://www.yavapaiaz.gov/County-Government/Board-of-Supervisors/Boards-and-Commissions/Water-Advisory-Committee",
"Central Yavapai Water Resource Study": "https://www.yavapaiaz.gov/files/sharedassets/public/v/1/resident-services/environmental-safety/documents/environmental_issues_assessment_and_alternative_descriptions_final_v4-4.pdf",
"Zuni Youth Enrichment Project - Water is Life": "https://www.zyep.org/zuni-families-conserve-water-and-save-money-through-the-zuni-youth-enrichment-projects-support-of-rain-harvest/",
"Enhancing Tribal Water Management Capacity in the Colorado River Basin: A Baseline Assessment": "https://www.waterandtribes.org/_files/ugd/1c5bb7_c3b7d7dbc21c4ceb9aacf49d23e6642e.pdf",
"General Plan-1": "https://www.apachejunctionaz.gov/DocumentCenter/View/20772/-Apache-Junction-GPU-2020-DIGITAL",
"General Plan-2": "https://webgen1files1.revize.com/cityofbensonaz/Document%20Center/Department/Planning%20and%20Zoning/General%20Plan/2015_Final_Draft.pdf",
"General Plan-3": "https://www.bisbeeaz.gov/DocumentCenter/View/1141/2015GeneralPlanUpdateVolume1Final_001June-2014?bidId=",
"Know Your Water Factsheet": "https://knowyourwaternews.com/wp-content/uploads/2020/12/CAP-Fact-Sheet-Know-Your-Water.pdf",
"Public Facilities": "https://eloyaz.gov/DocumentCenter/View/4935/38-Public-Facilities-Element",
"Pinal Creek Wastewater Treatment Facility": "https://www.globeaz.gov/public-works/pages/pinal-creek-wastewater-treatment-facility",
"Water-2.pdf": "https://www.globeaz.gov/public-works/pages/water",
"General Plan-5": "https://assets.website-files.com/5d110e58c64b3a3c65215b35/642b5c925902ed39c43ccf07_General%20Plan%208-9-05.pdf",
"General Plan-6": "https://www.cityofkingman.gov/home/showdocument?id=292",
"General Plan-7": "https://www.litchfieldpark.gov/DocumentCenter/View/11618/2022-General-Plan-033022-Approved-Final",
"Pima Water Resources Unit": "https://webgen1files1.revize.com/pimaaz/PIMA_GP%20(1).pdf",
"General Plan-9": "https://www.prescottvalley-az.gov/DocumentCenter/View/14355/Approved-General-Plan-2035",
"General Plan-10": "https://sahuaritaaz.gov/DocumentCenter/View/1169/Aspire-2035-Sahuaritas-General-Plan-Amended-2022?bidId=",
"General Plan-11": "https://www.sanluisaz.gov/DocumentCenter/View/10150/City-of-San-Luis-GP-2040",
"General Plan-13": "https://core-docs.s3.us-east-1.amazonaws.com/documents/asset/uploaded_file/4677/COSL/4023765/2018_GENERAL_PLAN_FINAL_201909101144128160__2_.pdf",
"General Plan-14": "https://cms2.revize.com/revize/somertonaz/document_center/Community%20Development/SGP_CouncilAdopted_060220.pdf",
"General Plan-15": "https://www.southtucsonaz.gov/sites/default/files/fileattachments/city_clerk/page/4753/city_of_south_tucson_chapter_22-_floodplain_pc.pdf",
"General Plan - Water Resources-3": "https://content.civicplus.com/api/assets/92746936-baf3-4b14-a50e-204c418083da?cache=1800",
"General Plan-17": "https://www.tayloraz.gov/wp-content/uploads/2014/01/2025-General-Plan.pdf",
"General Plan-18": "https://www.thatcher.az.gov/home/showpublisheddocument/1008/637901936330630000",
"General Plan-19": "https://www.tolleson.az.gov/DocumentCenter/View/2491/General-Plan-2024?bidId=",
"General Plan-20": "https://www.welltonaz.gov/sites/g/files/vyhlif8076/f/uploads/231214_final_adopted_wellton_2023_general_plan.pdf",
"General Plan-22": "https://tusayan-az.gov/wp-content/uploads/2023/06/2014-04-23-Tusayan-General-Plan-2024.pdf",
"General Plan-23": "https://cdnsm5-hosted.civiclive.com/UserFiles/Servers/Server_12608991/File/Our%20Services/Community%20Development/Directory%20of%20Regulatory%20Documents/6-24-14%20General%20Plan%202025%20-%20Final.pdf",
"General Plan-24": "https://www.yumaaz.gov/home/showpublisheddocument/5172/637939261174930000",
"Securing Our Water Future Through Advanced Water Purification": "https://www.amwua.org/blog/securing-our-water-future-through-advanced-water-purification",
"General Plan-4": "https://cottonwoodaz.gov/DocumentCenter/View/606/Water-Resources-PDF",
"General Plan (2009, most recent)": "https://drive.google.com/file/d/1A1SeL48R48CNZEX17T4RaeHAWAZIaOpf/view",
"General Plan-8": "https://drive.google.com/file/d/1CT7-L12DWcvZkGNG9eMq3fesVdsLtfx8/view?usp=drive_link",
"A Water / Energy Best Practices Guide for Rural Arizona’s Water & Wastewater Systems": "https://drive.google.com/file/d/1NzED78d48CE4NIv7qdWzSmAivkEPF8Fx/view?usp=drive_link",
"Nogales Water-2": "https://drive.google.com/file/d/1O0yA4PZTBGoPnfNJ7Jrg1BvBQCAV5SwQ/view?usp=drive_link",
"Public Works-3": "https://drive.google.com/file/d/1wXO7f0jalBPGgUSapGNGfYOvXKrYAZJJ/view?usp=drive_link",
"General Plan-12": "https://drive.google.com/file/d/1Bw2aY7H9En2wI_E8OB4AAPkANghKKOqB/view?usp=drive_link",
"General Plan-16": "https://content.civicplus.com/api/assets/92746936-baf3-4b14-a50e-204c418083da?cache=1800",
"General Plan-21": "https://drive.google.com/file/d/1cQenUYqsMbpenhaVquAjHW_S9wawJ-e2/view?usp=drive_link",
"Willcox Utilities": "https://drive.google.com/file/d/1PpawNSHapIuisHSc3juM8UWEPh2-RzHO/view?usp=drive_link",
"2024 Scottsdale Water Quality Report": "https://drive.google.com/file/d/1TC9N1dlqmcG9Au1Xy8b3k-ZLVjUy6JcN/view?usp=drive_link",
"Rural Water in Arizona": "https://docs.google.com/document/d/1TgddnnDf4SVyx59vOIy6UIYfs30FN_Cz/edit?usp=drive_link&ouid=105796556670555250653&rtpof=true&sd=true",
"Augmentation Concepts": "https://docs.google.com/document/d/10KrtHXDQw8w95rh1c0Yi7fYXLTurtdSj/edit?usp=drive_link&ouid=105796556670555250653&rtpof=true&sd=true",
"Brief History of Water Resources-2": "http://www.tonation-nsn.gov/water-resources/brief-history/",
"OVERVIEW OF THE ARIZONA GROUNDWATER MANAGEMENT CODE-2": "https://www.azwater.gov/sites/default/files/media/Arizona%20Groundwater_Code_1.pdf",
"HCC Water Master Plan Memo": "https://drive.google.com/file/d/1P9WXKbSfrGWJ9o4ML9lrHWTzW6WyaZD9/view",
"General Plan-25": "https://img1.wsimg.com/blobby/go/5f14fb93-ed4c-41ba-b8c4-d5ccaa1bf7c8/downloads/3%20Clifton%20General%20Plan%20Policy%20Plan%20-%20Final%208%201.pdf?ver=1720819747718",
"General Plan-26": "https://www.clarkdale.az.gov/DocumentCenter/View/997/Town-of-Clarkdale-2021-General-Plan-",
"General Plan-27": "https://www.cavecreekaz.gov/DocumentCenter/View/4413/2021-General-Plan---Cave-Creek?bidId=",
"COLORADO RIVER INDIAN TRIBES WATER RESILIENCY ACT OF 2022": "https://www.crit-nsn.gov/PLAW-117publ343.pdf",
"Water Conservation Brochure": "https://www.srpmic-nsn.gov/wp-content/uploads/2021/06/PW-WC2019Brochure.pdf",
"Water Conservation Page": "https://www.srpmic-nsn.gov/government/public-works/water-conservation/",
"Water Adjudication": "https://digitalrepository.unm.edu/cgi/viewcontent.cgi?article=1053&context=nawrs",
"Ak-Chin Indian Water Rights Settlement Act of 1978": "https://drive.google.com/file/d/1PQ11ev2Xn3rkYcwU1d6DFs4GhG2jvo9z/view?usp=drive_link",
"Tohono Oodham Water Rights Settlement Act of 1982 Title III": "https://drive.google.com/file/d/1MTct8u0SYtoVwX2U8aF-Lvu857ljBTUq/view?usp=drive_link",     
"1983 Agreement in Principle to Revise Ak-Chin Water Settlement": "https://drive.google.com/file/d/1H7zGAupEm7XU0si4fM9gwbq20dTOortx/view?usp=drive_link",  
"Salt River Pima-Maricopa Indian Community Water Rights Settlement (2)": "https://drive.google.com/file/d/1gOUecOdk3BLpfyYIQfo4rtJxavPvqgnM/view?usp=drive_link",
"Salt River Pima-Maricopa Indian Community Water Rights Settlement (1)": "https://drive.google.com/file/d/1bK1_JOx0xFX90wZZ6oxk42WHelYtS7jO/view?usp=drive_link",
"Fort McDowell Indian Community Water Rights Settlement of 1990 Ac": "https://drive.google.com/file/d/12KZY9NNhrjl7XlPnqXj4lG7-s-yrBdcP/view?usp=drive_link",
"Salt River Pima-Maricopa Indian Community Water Rights Settlement of 1991": "https://drive.google.com/file/d/14IjlbMeF8wPALBB1zOm6yZgcBmpA3n-u/view?usp=drive_link",
"Technical Amendments to Southern Arizona Water Rights Settlement": "https://drive.google.com/file/d/1-UFJb9Vuc5evBOCWoBm0pI89zZIvQqv7/view?usp=drive_link",
"San Carlos Apache Tribe Water Rights Settlement Act of 1992 San": "https://drive.google.com/file/d/1aUVlDzzSqQx1AFObylOSc4CIsmXN_Go4/view?usp=drive_link", 
"1992 Amendments 1984 Ak-Chin Water Act (1)": "https://drive.google.com/file/d/1y0eyKjxTTfTPIlIyCWoccIL-tGcrvoV5/view?usp=sharing",
"Fort McDowell Indian Community Water Settlement (Yavapai Nation)": "https://drive.google.com/file/d/10l9or1hc2T-s_EbW258FtV7uCYhQ4Huf/view?usp=drive_link",
"Yavapai-Prescott Indian Water Rights Settlement Act of 1994": "https://drive.google.com/file/d/1aH9zxpLz3P4Gz2hiGSF1eBLyL3EQHz2W/view?usp=drive_link",     
"San Carlos Apache Tribe Water Rights Settlement Act of 1992 Amen": "https://drive.google.com/file/d/1Pmu4yxESqaWM3B5SAf4XIqXRnCw6c816/view?usp=drive_link",
"An Act to Provide for the Settlement of the Water Rights Claims of Yavapai": "https://drive.google.com/file/d/1j3PW1DI--bGXFPU1zFxrXir9GW4W_AGO/view?usp=drive_link",
"Yavapai-Prescott Indian Tribe Water Rights Settlement of 1994 Am": "https://drive.google.com/file/d/1h0VXgtMuzTx9yTmxtWUYw_lJ4uP05LdW/view?usp=drive_link",
"San Carlos Apache Tribe Amendments to Act of 1992 1997 Amendment": "https://drive.google.com/file/d/1E6lTUrTlpxtMb3PDjA-8Ep3T2fSmhBMN/view?usp=drive_link",
"San Carlos Apache Tribe Water Rights Settlement Agreement of 1999": "https://drive.google.com/file/d/1MJ5H2sGqdUKclAEA-vD-m-lN22ppbh2F/view?usp=drive_link",
"Zuni Indian Tribe Water Rights Settlement in the Little CO River": "https://drive.google.com/file/d/18ro5k2PKHOm2nxS1jfpmoMePw4Zf7WhJ/view?usp=drive_link",
"Zuni Indian Tribe Water Rights Settlement Act of 2003": "https://drive.google.com/file/d/1eASZoeQYE2ZjY0VFvykgcHnXcYLjbUwB/view?usp=drive_link",
"Tohono Oodham Settlement": "https://drive.google.com/file/d/1lTFRCaIexshWP7CkJ2tRHbSRMBtN_41A/view?usp=drive_link",
"Gila River Indian Community Water Rights Settlement Act of 2004": "https://drive.google.com/file/d/1n6K9eA4pwgxZvrRGc6g38O4w5al9cKFj/view?usp=drive_link", 
"Amendment No. 1 to the Zuni Indian Tribe Water Rights Settlement": "https://drive.google.com/file/d/1AjV9YxM5i26xNOYR2zoRmq_Tz1PQSx_q/view?usp=drive_link",
"2005 Amended and Restated Gila River Indian Community Water Right": "https://drive.google.com/file/d/1bUyGcH5mg0-XAE8F4D-WWsN18434Xqhe/view?usp=drive_link",
"Fort McDowell Indian Community Water Rights Settlement Revision A": "https://drive.google.com/file/d/1NEzvg-0vRXjBhA0BCmE-4Ac6SOBTyJB-/view?usp=drive_link",
"Amendment No. 1 to the Amended and Restated Gila River Indian Com": "https://drive.google.com/file/d/1HWBgc5KYNbfZR6o4asFETqZ2VGS5Ddkl/view?usp=drive_link",
"Amended and Restated Gila River Indian Community Water Rights Amendment 2 2007": "https://drive.google.com/file/d/1OHh8RdcdJu9EshDMRCLmXxkiu8Pa0gMh/view?usp=drive_link",
"White Mountain Apache Tribe Water Rights Quantification Act of 2010": "https://drive.google.com/file/d/15jpmbSHHQrooHGl_gE-PUNY79c11oaSl/view?usp=drive_link",
"Amended and Restated White Mountain Apache Tribe Water Rights Qua": "https://drive.google.com/file/d/18mm3EiJr0syymQ9S83uCxqZOYGnEcrrr/view?usp=drive_link",
"White Mountain Apache Water Rights Quantification Settlement Judg": "https://drive.google.com/file/d/1UtUKHiC_U5czXfiyl8k5-8o0ZUVXDfO1/view?usp=drive_link",
"Bill Williams River Water Rights Settlement Act of 2014": "https://drive.google.com/file/d/1yWMkwj0zKcLamC2RS_W7toY_D3qy2i2j/view?usp=drive_link",
"White Mountain Apache Tribe Water Rights Quantification Act": "https://drive.google.com/file/d/1HQPSqvCZ7oItOkhh9zMyIe4y9QwwgqxN/view?usp=drive_link",     
"Hualapai Tribe Water Rights Settlement Act of 2022": "https://drive.google.com/file/d/1BENEONXHWDJoznXJKaarCODhI9xZ6KvN/view?usp=drive_link",
"Ak-Chin Settlement Act of 1984": "https://drive.google.com/file/d/1-0dmg3cM-I0SySpeAJGCQupL7VBGkFLH/view?usp=drive_link",
"1992 Amendments 1984 Ak-Chin Water Act": "https://drive.google.com/file/d/1kvECq3CVSfdY7PEZDfCkNiKGqzcoBdaI/view?usp=drive_link",
"Ak-Chin Water Use Act of 1984 2000 Amendments": "https://drive.google.com/file/d/1MP7fIl_TU1ERDBl0IqHqK0ZJIlitaFCa/view?usp=drive_link",
"Fort Mojave Indian Tribe - Keepers of the River": "https://drive.google.com/file/d/1wdn04ge8T0k_rh7Up7-ZC-I4GdBRcjkc/view?usp=drive_link",
"Rights to Use Water in the Gila River System.pdf": "https://drive.google.com/file/d/1CKves3-ZmwQq2IIrIklRI3E3TI1ETyVN/view?usp=drive_link",
"2023 Consumer Confidence Report.pdf": "https://www.tempe.gov/home/showdocument?id=108032&t=638514514522921469",
"Arizona Department of Water Resources.pdf": "https://drive.google.com/file/d/1JUlZlpUoR_bdEWR9R1fMLcn8PJ6ZFmGq/view?usp=drive_link",
"Superior General Plan.pdf": "https://drive.google.com/file/d/1uuDRq01sar1zfAPUOa5k1Gb-3wpF_tEm/view?usp=drive_link",
"100+ Water Saving Tips.pdf": "https://wateruseitwisely.com/100-ways-to-conserve-water/",
"Arizona Public School Drinking Water Lead Screening Program.pdf": "https://azdeq.gov/node/3634",
"Water Quality-2.pdf": "https://www.queencreekaz.gov/home/showpublisheddocument/38216/638235484870300000",
"Colorado River Interim Guidelines for Lower Basin Shortages.pdf": "https://www.usbr.gov/lc/region/programs/strategies/RecordofDecision.pdf",
"OPERATION PLAN FOR COLORADO RIVER RESERVOIRS.pdf": "https://www.usbr.gov/lc/region/g4000/24mo.pdf",
"California's Water Supply Strategy.pdf": "https://resources.ca.gov/-/media/CNRA-Website/Files/Initiatives/Water-Resilience/CA-Water-Supply-Strategy.pdf",  
"Arizona Water Banking Authority Annual Plan of Operation 2023 (Plan de operaciones anual de la autoridad bancaria de agua de Arizona 2023).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Arizona Water Banking Authority Annual Report 2022 (Informe anual de la Autoridad Bancaria de Agua de Arizona 2022).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Arizona Water Fact Sheet Maricopa County (Hoja Informativa Sobre el Agua de Arizona Condado de Maricopa).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Colorado River Interim Guidelines for Lower Basin Shortages and the Coordinated Operations for Lake Powell and Lake Mead .pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"How to be Efficient and Effective with Your Outdoor Watering (Cómo ser eficiente y efectivo con su riego al aire libre).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Issues We're Facing (Problemas que enfrentamos).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Lessons from the Past (Lecciones del pasado).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"NCA5_Ch11_Agriculture_esp.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"NCA5_Ch16_Tribes-and-Indigenous-Peoples_esp.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"NCA5_Ch1_Overview_esp.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"NCA5_Ch28_Southwest_esp.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"NCA5_Ch31_Adaptation_esp.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"NCA5_Ch32_Mitigation_esp.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"NCA5_Ch4_Water_esp.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"OMWUA One for Water.pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Overview of the Arizona Groundwater Management Code (Descripción General del Código de Gestión de Aguas Subterráneas de Arizona).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Precision Agriculture (Agricultura de precisión).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Reclamation Confirms a Tier 1 Colorado River Shortage for 2024 (Reclamation confirma una escasez de nivel 1 en el río Colorado para 2024).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Return to Watering the Sun Corridor (Regreso a regando el corredor solar).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"The Arizona Drought Contingency: A Tribal Perspective (Plan de Contingencia ante Sequía de Arizona: Una Perspectiva Tribal).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"The Elusive Concept of an Assured Water Supply: The Role of CAGRD and Replenishment (El elusivo concepto de un suministro de agua asegurado: El papel de CAGRD y Reabastecimiento).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"The Future of Water in Arizona (El futuro del agua en Arizona).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Tohono O'odham Brief History of Water Resources Department (Breve historia del Departamento de Recursos Hídricos de Tohono O'odham).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Tribal Water Supply: An Overview (Estudio tribal sobre el agua: una visión general).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Untangling Housing Affordability & Groundwater Regulation (Desentrañando la asequibilidad de la vivienda y la regulación de las aguas subterráneas).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
"Water and Waste Water (Agua y aguas residuales).pdf": "https://drive.google.com/drive/folders/1QgemZWUva8f1X7oCbpxDjETL1cZdW_25",
}

def LookupWebsource(filename):
    websource = source_dict.get(filename)
    if websource:
        return websource
    else:
        print('File not found')
        return 'File websource not found.'
